//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartTable
    {
        public int CartID { get; set; }
        public long FirebaseID { get; set; }
        public int CustomerID { get; set; }
        public int PaymentID { get; set; }
        public string ProductsIDS { get; set; }
    
        public virtual CustomerTable CustomerTable { get; set; }
        public virtual PaymentTable PaymentTable { get; set; }
    }
}
