//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommentTable()
        {
            this.Product_Table = new HashSet<Product_Table>();
        }
    
        public int CommentID { get; set; }
        public string Comment { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime CommentDate { get; set; }
        public int ProductID { get; set; }
        public int Point { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Table> Product_Table { get; set; }
    }
}
