//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcommerDBEntities : DbContext
    {
        public EcommerDBEntities()
            : base("name=EcommerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnneBOTable> AnneBOTable { get; set; }
        public virtual DbSet<CartTable> CartTable { get; set; }
        public virtual DbSet<Category_Table> Category_Table { get; set; }
        public virtual DbSet<CommentTable> CommentTable { get; set; }
        public virtual DbSet<CustomerTable> CustomerTable { get; set; }
        public virtual DbSet<ElectronicPTable> ElectronicPTable { get; set; }
        public virtual DbSet<EvYKOPTable> EvYKOPTable { get; set; }
        public virtual DbSet<KitapMFHTable> KitapMFHTable { get; set; }
        public virtual DbSet<KozmetikKTable> KozmetikKTable { get; set; }
        public virtual DbSet<ModaPTable> ModaPTable { get; set; }
        public virtual DbSet<OrdersTable> OrdersTable { get; set; }
        public virtual DbSet<OtoBYMTable> OtoBYMTable { get; set; }
        public virtual DbSet<PaymentTable> PaymentTable { get; set; }
        public virtual DbSet<Product_Table> Product_Table { get; set; }
        public virtual DbSet<ProductInfo> ProductInfo { get; set; }
        public virtual DbSet<SporOTable> SporOTable { get; set; }
        public virtual DbSet<SubCategoriesTable> SubCategoriesTable { get; set; }
        public virtual DbSet<SupermarketPKTable> SupermarketPKTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
