//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Table()
        {
            this.AnneBOTable = new HashSet<AnneBOTable>();
            this.EvYKOPTable = new HashSet<EvYKOPTable>();
            this.KitapMFHTable = new HashSet<KitapMFHTable>();
            this.KozmetikKTable = new HashSet<KozmetikKTable>();
            this.ModaPTable = new HashSet<ModaPTable>();
            this.OrdersTable = new HashSet<OrdersTable>();
            this.OtoBYMTable = new HashSet<OtoBYMTable>();
            this.SporOTable = new HashSet<SporOTable>();
            this.SupermarketPKTable = new HashSet<SupermarketPKTable>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Stock { get; set; }
        public int ProductInfoID { get; set; }
        public decimal Price { get; set; }
        public string Mark { get; set; }
        public short CategoryID { get; set; }
        public int CommentID { get; set; }
        public string PhotoUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnneBOTable> AnneBOTable { get; set; }
        public virtual Category_Table Category_Table { get; set; }
        public virtual CommentTable CommentTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvYKOPTable> EvYKOPTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitapMFHTable> KitapMFHTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KozmetikKTable> KozmetikKTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModaPTable> ModaPTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersTable> OrdersTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtoBYMTable> OtoBYMTable { get; set; }
        public virtual ProductInfo ProductInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SporOTable> SporOTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupermarketPKTable> SupermarketPKTable { get; set; }
    }
}
