//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI3
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoriesTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubCategoriesTable()
        {
            this.ElectronicPTable = new HashSet<ElectronicPTable>();
        }
    
        public int SubCategoriesID { get; set; }
        public string SubCategoriesName { get; set; }
        public short CategoryID { get; set; }
    
        public virtual Category_Table Category_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicPTable> ElectronicPTable { get; set; }
    }
}
